## Ejercicio 1
Crea una función que dado un Array de una dimensión, te haga un resumen estadístico básico de los datos. Si detecta que el array tiene más de una dimensión, debe mostrar un mensaje de error.

In [82]:
import numpy as np

import statistics
from statistics import mean, mode, multimode, stdev

#Crear un array unidimensional
dataOneDimension = np.random.randint(10, size=(6)) 

#Crear un array con dos dimensiones
dataTwoDimensions = np.random.randint(10, size=(2, 6)) 


def ResumenDeEstadistico(data):
    if data.ndim == 1:
        print("La media del array es", statistics.mean(data), "su desviación estandar es de",
              round(float(stdev(data)), 1), "La mediana de la lista es", statistics.median(data),
              "con moda de", statistics.mode(data))
    else: 
        print("Error, el array tiene más de una dimensión")

#Testear la función con el array de una dimensión
ResumenDeEstadistico(dataOneDimension)

#Testear la función con el array de dos dimensiones
ResumenDeEstadistico(dataTwoDimensions)


La media del array es 3 su desviación estandar es de 2.8 La mediana de la lista es 3.0 con moda de 2
Error, el array tiene más de una dimensión


## Ejercicio 2
Crea una función que genere un cuadrado NxN de números aleatorios entre el 0 y el 100.

In [13]:
import numpy as np   

def cuadro():
    numero = input("Ingrese la cantidad de números: ")
    numero=int(numero)
    array = np.random.randint(100, size=(numero, numero)) 
    print(array) 

cuadro()

Ingrese la cantidad de números: 5
[[98 67 40 42 95]
 [98 50 55 43 82]
 [93 97 29 95 57]
 [58 29 65  4 24]
 [90 57 68 59 31]]


##  Ejercicio 3
Crea una función que dada una tabla de dos dimensiones, te calcule los totales por fila y los totales por columna.

In [78]:
def columna_fila(lst): 
    columna= [sum(i) for i in zip(*lst)]
    df2 = lst.sum(axis=1)
    print("La tabla es",lst, 
          "\n La sumatoria de la primer fila es", df2[0], "la sumatoria de la segunda fila es", df2[1], 
          "\n La sumatoria por columnas es", column_sum(dataTwoDimensions))
    
columna_fila(dataTwoDimensions)

La tabla es [[3 4 8 4 4 9]
 [1 0 3 8 9 8]] 
 La sumatoria de la primer fila es 32 la sumatoria de la segunda fila es 29 
 La sumatoria por columnas es [4, 4, 11, 12, 13, 17]


##  Ejercicio 4
Implementa manualmente una función que calcule el coeficiente de correlación. Infórmate sobre sus usos e interpretación.

In [130]:
import math, statistics


def correlacion(x,y):
    #Primer paso: Calcular el promedio de las variables
    suma_x = sum(x)
    suma_y = sum(y)
    n = len(x)
    x_mean = statistics.mean(x)
    y_mean = statistics.mean(y)
    dividendo = 0.0
    divisor = 0.0
    Tercer_paso_x = 0.0
    Tercer_paso_y = 0.0
    #Segundo paso, calcular el dividendo (arriba)
    for i in range(n):
        dividendo += (x[i]-x_mean)*(y[i]-y_mean)
    #Tercer paso, calcular el divisor (abajo)
    for i in range(n):
        Tercer_paso_x += (x[i] - x_mean)*(x[i]-x_mean)
    for i in range(n):
        Tercer_paso_y += (y[i] - y_mean) * (y[i] - y_mean)
    divisor = math.sqrt(Tercer_paso_x*Tercer_paso_y)
    #Cuarto paso: realizar la división
    resultado = dividendo/divisor
    print("La correlación entre las variables es ", resultado)

# Evaluar si la función es correcta
x_simple = np.array([-2, -1, 0, 1, 2])
y_simple = np.array([4, 1, 3, 2, 0])
correlacion(x_simple, y_simple)


#Para comprobar el resultado de la función con la formula del programa
print(np.corrcoef(x_simple, y_simple))


La correlación entre las variables es  -0.7
[[ 1.  -0.7]
 [-0.7  1. ]]
